# 1 Stages of pipeline, should match with stage tag inside each job.
# Each stages executes in sequence, if previous job fails, then all the preceeding jobs are skipped.
stages:
    - mavenbuild
    - maventest
    - autodeploy
    - androidbuild

# tags: "shell" should match with the tag name provided to runner, for spring runner should execute in shell.
# Notice that in petclinic project, the spring project is in root of master, if yours is in folder then cd to that folder.
maven-build:
  stage: mavenbuild
  tags:
    - Back-end
  script:
  - cd Backend/CyCHORE/CyCHORE
  - mvn package -B
  
# artifacts are created when job executes successfully, and can be manually downloaded from GitLab GUI.
# artifacts are not mandatory, buts it good practice, in case auto deploy fails, you can manually download the jar.
maven-test:
  stage: maventest
  tags:
    - Back-end
  script:
    - cd Backend/CyCHORE/CyCHORE
    - mvn test
  artifacts:
    paths:
    - Spring/target/*.jar
    
    

android-build:
    image: javiersantos/android-ci:latest
    stage: androidbuild
    before_script: 
        - export GRADLE_USER_HOME=`pwd`/.gradle
        - chmod +x ./FrontEnd/CyChore/gradlew
    tags:
        - Front-end
    script:
        - cd FrontEnd/CyChore
        - ./gradlew assemble 
    artifacts:
        paths:
        - androidTest/app/build/outputs


